##**Costeo 2025: Fortalecimiento de los servicios educativos en los centros de educación básica alternativa para la atención de estudiantes con discapacidad - DEBA**



*   Autor: Manuel Reyes Quispe
*   Equipo: Analítica de Datos y Programación de Presupuesto Territorial

In [1]:
# pip install dbfread
# pip install openpyxl

In [2]:
import pandas as pd
import numpy as np
from dbfread import DBF
from os import write

In [3]:
# importamos la base de metas peas CAS
peas = pd.read_excel('D:/2025/IAP/Interpretes DEBA/input/Metas_contratacion_InterpretesEBA.xlsx', skiprows=2, dtype={'Código Local': str, 'Código Modular': str,'Anexo':str})

peas = peas.iloc[:-1] # eliminamos la última fila que registra el total

peas.head(5)

,Pliego,Unidad Ejecutora,DRE/UGEL,Código Modular,Anexo,Código Local,NOMBRE DE CEBA,Modelo Lingüístico de lengua de señas peruana para EBA,Intérprete de lengua de señas peruana para EBA
0,10. LIMA METROPOLITANA,001. USE 01 SAN JUAN DE MIRAFLORES,Ugel 01 San Juan De Miraflores,1724715,0,343852,PAEBA VILLA EL SALVADOR,0,1
1,10. LIMA METROPOLITANA,001. USE 01 SAN JUAN DE MIRAFLORES,Ugel 01 San Juan De Miraflores,1315316,0,343852,PAEBA VILLA EL SALVADOR,2,5
2,10. LIMA METROPOLITANA,003. USE 03 CERCADO,Ugel 03 Breña,0605618,0,288092,0040 HIPOLITO UNANUE,0,1
3,10. LIMA METROPOLITANA,003. USE 03 CERCADO,Ugel 03 Breña,0337345,0,288092,0040 HIPOLITO UNANUE,2,6
4,10. LIMA METROPOLITANA,004. USE 04 COMAS,Ugel 04 Comas,0830968,0,301625,2048 JOSE CARLOS MARIATEGUI,2,2

In [4]:
# llevamos la base de metas CAS a un formato long
peas_long = pd.melt(peas, id_vars=['Pliego', 'Unidad Ejecutora', 'DRE/UGEL', 'Código Modular', 'Anexo', 'Código Local', 'NOMBRE DE CEBA'],
                    value_vars=['Intérprete de lengua de señas peruana para EBA','Modelo Lingüístico de lengua de señas peruana para EBA'],
                    var_name='Perfil', value_name='PEAS')

peas_long = peas_long[peas_long['PEAS'] > 0]

peas_long.head(5)

,Pliego,Unidad Ejecutora,DRE/UGEL,Código Modular,Anexo,Código Local,NOMBRE DE CEBA,Perfil,PEAS
0,10. LIMA METROPOLITANA,001. USE 01 SAN JUAN DE MIRAFLORES,Ugel 01 San Juan De Miraflores,1724715,0,343852,PAEBA VILLA EL SALVADOR,Intérprete de lengua de señas peruana para EBA,1
1,10. LIMA METROPOLITANA,001. USE 01 SAN JUAN DE MIRAFLORES,Ugel 01 San Juan De Miraflores,1315316,0,343852,PAEBA VILLA EL SALVADOR,Intérprete de lengua de señas peruana para EBA,5
2,10. LIMA METROPOLITANA,003. USE 03 CERCADO,Ugel 03 Breña,0605618,0,288092,0040 HIPOLITO UNANUE,Intérprete de lengua de señas peruana para EBA,1
3,10. LIMA METROPOLITANA,003. USE 03 CERCADO,Ugel 03 Breña,0337345,0,288092,0040 HIPOLITO UNANUE,Intérprete de lengua de señas peruana para EBA,6
4,10. LIMA METROPOLITANA,004. USE 04 COMAS,Ugel 04 Comas,0830968,0,301625,2048 JOSE CARLOS MARIATEGUI,Intérprete de lengua de señas peruana para EBA,2

In [5]:
# Leer el archivo DBF como una lista de diccionarios - importamos el padron web del escale al corte del 20.12.2024
records = DBF('D:/2025/IAP/Interpretes DEBA/input/Padron_web_20241220.dbf', load=True)

# Convertir a un DataFrame de pandas
padron = pd.DataFrame(iter(records))

In [6]:
# validacion de metas peas
peas_long_2 = peas_long.iloc[:,2:]
peas_long_2['id'] = pd.to_numeric(peas_long_2['Código Modular'] + peas_long_2['Anexo'], errors='coerce')

peas_long_2

,DRE/UGEL,Código Modular,Anexo,Código Local,NOMBRE DE CEBA,Perfil,PEAS,id
0,Ugel 01 San Juan De Miraflores,1724715,0,343852,PAEBA VILLA EL SALVADOR,Intérprete de lengua de señas peruana para EBA,1,17247150
1,Ugel 01 San Juan De Miraflores,1315316,0,343852,PAEBA VILLA EL SALVADOR,Intérprete de lengua de señas peruana para EBA,5,13153160
2,Ugel 03 Breña,0605618,0,288092,0040 HIPOLITO UNANUE,Intérprete de lengua de señas peruana para EBA,1,6056180
3,Ugel 03 Breña,0337345,0,288092,0040 HIPOLITO UNANUE,Intérprete de lengua de señas peruana para EBA,6,3373450
4,Ugel 04 Comas,0830968,0,301625,2048 JOSE CARLOS MARIATEGUI,Intérprete de lengua de señas peruana para EBA,2,8309680
5,Ugel 06 Ate,0315259,0,338817,1137 JOSE ANTONIO ENCINAS,Intérprete de lengua de señas peruana para EBA,1,3152590
6,Ugel 06 Ate,0601740,0,338817,1137 JOSE ANTONIO ENCINAS,Intérprete de lengua de señas peruana para EBA,1,6017400
7,Ugel Arequipa Norte,1666254,0,055417,POLIVALENTE,Intérprete de lengua de señas peruana para EBA,4,16662540
8,Ugel Cusco,0497628,0,146154,HUMBERTO LUNA,Intérprete de lengua de señas peruana para EBA,4,4976280
9,Ugel Quispicanchi,1724244,0,168117,51030 LUIS NAVARRETE,Intérprete de lengua de señas peruana para EBA,1,17242440
10,Ugel 03 - Trujillo Nor Oeste,1729276,0,744251,81014 PEDRO MERCEDES UREÑA,Intérprete de lengua de señas peruana para EBA,1,17292760
11,Ugel 03 - Trujillo Nor Oeste,0394767,0,250249,VICTOR ANDRES BELAUNDE,Intérprete de lengua de señas peruana para EBA,2,3947670
12,Ugel Maynas,0738534,0,365212,60026 RUY GUZMAN HIDALGO,Intérprete de lengua de señas peruana para EBA,1,7385340
13,Ugel Maynas,1148410,0,365212,60026 RUY GUZMAN HIDALGO,Intérprete de lengua de señas peruana para EBA,3,11484100
14,Ugel Maynas,1360023,0,366056,BELEN,Intérprete de lengua de señas peruana para EBA,1,13600230
15,Ugel Maynas,0685131,0,366056,BELEN,Intérprete de lengua de señas peruana para EBA,1,6851310
16,Ugel Maynas,0302836,0,365900,MARISCAL OSCAR R. BENAVIDES,Intérprete de lengua de señas peruana para EBA,1,3028360
18,Ugel 01 San Juan De Miraflores,1315316,0,343852,PAEBA VILLA EL SALVADOR,Modelo Lingüístico de lengua de señas peruana ...,2,13153160
20,Ugel 03 Breña,0337345,0,288092,0040 HIPOLITO UNANUE,Modelo Lingüístico de lengua de señas peruana ...,2,3373450
21,Ugel 04 Comas,0830968,0,301625,2048 JOSE CARLOS MARIATEGUI,Modelo Lingüístico de lengua de señas peruana ...,2,8309680
22,Ugel 06 Ate,0315259,0,338817,1137 JOSE ANTONIO ENCINAS,Modelo Lingüístico de lengua de señas peruana ...,1,3152590
24,Ugel Arequipa Norte,1666254,0,055417,POLIVALENTE,Modelo Lingüístico de lengua de señas peruana ...,1,16662540
25,Ugel Cusco,0497628,0,146154,HUMBERTO LUNA,Modelo Lingüístico de lengua de señas peruana ...,1,4976280
26,Ugel Quispicanchi,1724244,0,168117,51030 LUIS NAVARRETE,Modelo Lingüístico de lengua de señas peruana ...,1,17242440
27,Ugel 03 - Trujillo Nor Oeste,1729276,0,744251,81014 PEDRO MERCEDES UREÑA,Modelo Lingüístico de lengua de señas peruana ...,1,17292760
28,Ugel 03 - Trujillo Nor Oeste,0394767,0,250249,VICTOR ANDRES BELAUNDE,Modelo Lingüístico de lengua de señas peruana ...,1,3947670
29,Ugel Maynas,0738534,0,365212,60026 RUY GUZMAN HIDALGO,Modelo Lingüístico de lengua de señas peruana ...,1,7385340
30,Ugel Maynas,1148410,0,365212,60026 RUY GUZMAN HIDALGO,Modelo Lingüístico de lengua de señas peruana ...,1,11484100
31,Ugel Maynas,1360023,0,366056,BELEN,Modelo Lingüístico de lengua de señas peruana ...,1,13600230
32,Ugel Maynas,0685131,0,366056,BELEN,Modelo Lingüístico de lengua de señas peruana ...,1,6851310
33,Ugel Maynas,0302836,0,365900,MARISCAL OSCAR R. BENAVIDES,Modelo Lingüístico de lengua de señas peruana ...,1,3028360

In [7]:
# nos quedamos con campos relevantes del padron web importado
padron_2 = padron[['COD_MOD', 'ANEXO', 'CODLOCAL', 'CEN_EDU', 'CODOOII','D_DREUGEL']]

padron_2['id'] = pd.to_numeric(padron_2['COD_MOD'] + padron_2['ANEXO'], errors='coerce')

padron_2.head(5)

C:\Users\COORDINADORUPP3\AppData\Local\Temp\ipykernel_40208\2030422795.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  padron_2['id'] = pd.to_numeric(padron_2['COD_MOD'] + padron_2['ANEXO'], errors='coerce')

,COD_MOD,ANEXO,CODLOCAL,CEN_EDU,CODOOII,D_DREUGEL,id
0,0415547,0,016100,123,020001,UGEL HUARAZ,4155470
1,0415638,0,015172,122,020001,UGEL HUARAZ,4156380
2,0415646,0,015186,233,020001,UGEL HUARAZ,4156460
3,0415877,0,016751,COLEGIO PARROQUIAL NUESTRA SEÑORA DEL SAGRADO ...,020001,UGEL HUARAZ,4158770
4,0567206,0,016119,268,020001,UGEL HUARAZ,5672060

In [8]:
# realizamos el join entre la la base de metas cas y el padron web
peas_long_3 = pd.merge(peas_long_2, padron_2, on='id', how='left')

peas_long_4 = peas_long_3[['Perfil','PEAS','COD_MOD','ANEXO','CODLOCAL','CEN_EDU','CODOOII']]

peas_long_4.head(5)

,Perfil,PEAS,COD_MOD,ANEXO,CODLOCAL,CEN_EDU,CODOOII
0,Intérprete de lengua de señas peruana para EBA,1,1724715,0,343852,PAEBA VILLA EL SALVADOR,150102
1,Intérprete de lengua de señas peruana para EBA,5,1315316,0,343852,PAEBA VILLA EL SALVADOR,150102
2,Intérprete de lengua de señas peruana para EBA,1,0605618,0,288092,0040 HIPOLITO UNANUE,150104
3,Intérprete de lengua de señas peruana para EBA,6,0337345,0,288092,0040 HIPOLITO UNANUE,150104
4,Intérprete de lengua de señas peruana para EBA,2,0830968,0,301625,2048 JOSE CARLOS MARIATEGUI,150105

In [9]:
# importamos la base de ugel-ubigeo que nos permitirá incorporar el Pliego, UE, Ugel con el nombre correcto y homogéneo
ugel = pd.read_excel('D:/2025/IAP/Interpretes DEBA/input/base_ue_ugel_ubigeo_2024.xlsx', sheet_name='base' ,dtype={'CODOOII': str})

ugel['CODOOII'] = ugel['CODOOII'].astype(str).str.zfill(6)

ugel = ugel[~ugel['UGEL'].str.contains('COLEGIO MILITAR', na=False)]
ugel = ugel[~ugel['NOM_UE'].str.contains('COLEGIO MILITAR', na=False)]

In [10]:
# realizamos el join para incorporar los campos con nombres correctos
peas_long_5 = pd.merge(peas_long_4, ugel, on = 'CODOOII', how='left')

# Definir el orden de las columnas
column_order = ['PLIEGO','NOM_PLIEGO','EJECUTORA','NOM_UE','CODOOII','UGEL','COD_MOD','ANEXO','CODLOCAL','CEN_EDU','Perfil', 'PEAS']

# Reordenar las columnas del DataFrame
peas_long_5 = peas_long_5[column_order]

peas_long_5.to_excel('D:/2025/IAP/Interpretes DEBA/output/MEF/METAS_PEAS_VAL_2025.xlsx', index=False) # este insumo sería la base de metas cas validado

**COSTEO SIAF**

In [11]:
peas_siaf = peas_long_5

import math

# costos
rem_1 = 1500 # remuneración base:Intérprete de lengua de señas peruana para EBA
rem_2 = 1150 # remuneración base:Modelo Lingüístico de lengua de señas peruana para EBA
nc = 50 + 64.19 + 50 + 100 # negociaciones colectivas
agui_1 = 300  # aguinaldo julio
agui_2 = 300  # aguinaldo diciembre


def calcular_essalud(remuneraciones, uit):
    essalud = []  # Lista para almacenar los resultados

    # Bucle para recorrer cada valor de remuneración
    for rem in remuneraciones:
        # Cálculo
        valor1 = 0.09 * rem
        valor2 = uit * 0.45 * 0.09

        # Redondear hacia arriba (equivalente a REDONDEAR.MAS en Excel)
        redondeado1 = round(valor1)
        redondeado2 = round(valor2)

        # Condicional para determinar el valor de essalud
        essalud_valor = redondeado1 if redondeado1 <= redondeado2 else redondeado2

        # Agregar el resultado a la lista
        essalud.append(essalud_valor)

    return essalud


# Ejemplo de uso
remuneraciones = [math.ceil(rem_1+nc),math.ceil(rem_2+nc)]  # Lista de remuneraciones
uit = 5350    # Valor UIT

resultados = calcular_essalud(remuneraciones, uit)


peas_siaf.head(5)

remuneraciones
resultados

[159, 127]

In [12]:

# calendario
mes_1 = 10  # Perfil_1 : marzo - diciembre
mes_2 = 10  # Perfil_2 : marzo - diciembre

meses_12 = ['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre']
meses_11 = ['febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre']
meses_10 = ['marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre']
meses_9 = ['abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre']
meses_8 = ['mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre']
meses_7 = ['junio','julio','agosto','septiembre','octubre','noviembre','diciembre']
meses_6 = ['julio','agosto','septiembre','octubre','noviembre','diciembre']
meses_5 = ['agosto','septiembre','octubre','noviembre','diciembre']
meses_4 = ['septiembre','octubre','noviembre','diciembre']
meses_3 = ['octubre','noviembre','diciembre']
meses_2 = ['noviembre','diciembre']
meses_1 = ['diciembre']


# Crear la nueva columna 'perfil_cod' basada en el campo 'perfil'
peas_siaf['perfil_cod'] = 'perfil_' + (peas_siaf.groupby('Perfil').ngroup() + 1).astype(str)

peas_siaf['cas_anual'] = np.where(peas_siaf['perfil_cod'] == 'perfil_1', remuneraciones[0] * mes_1 * peas_siaf['PEAS'],
                                                                         remuneraciones[1] * mes_2 * peas_siaf['PEAS'])

peas_siaf['essalud_anual'] = np.where(peas_siaf['perfil_cod'] == 'perfil_1', resultados[0]*mes_1*peas_siaf['PEAS'],
                                                                             resultados[1]*mes_2*peas_siaf['PEAS'])

peas_siaf['aguinaldo_anual'] = np.where(peas_siaf['perfil_cod'] == 'perfil_1', agui_1  * peas_siaf['PEAS']*2,
                                                                               agui_2  * peas_siaf['PEAS']*2)

peas_siaf.head(5)

,PLIEGO,NOM_PLIEGO,EJECUTORA,NOM_UE,CODOOII,UGEL,COD_MOD,ANEXO,CODLOCAL,CEN_EDU,Perfil,PEAS,perfil_cod,cas_anual,essalud_anual,aguinaldo_anual
0,10,10. LIMA METROPOLITANA,1,001. USE 01 SAN JUAN DE MIRAFLORES,150102,UGEL 01 SAN JUAN DE MIRAFLORES,1724715,0,343852,PAEBA VILLA EL SALVADOR,Intérprete de lengua de señas peruana para EBA,1,perfil_1,17650,1590,600
1,10,10. LIMA METROPOLITANA,1,001. USE 01 SAN JUAN DE MIRAFLORES,150102,UGEL 01 SAN JUAN DE MIRAFLORES,1315316,0,343852,PAEBA VILLA EL SALVADOR,Intérprete de lengua de señas peruana para EBA,5,perfil_1,88250,7950,3000
2,10,10. LIMA METROPOLITANA,3,003. USE 03 CERCADO,150104,UGEL 03 BREÑA,0605618,0,288092,0040 HIPOLITO UNANUE,Intérprete de lengua de señas peruana para EBA,1,perfil_1,17650,1590,600
3,10,10. LIMA METROPOLITANA,3,003. USE 03 CERCADO,150104,UGEL 03 BREÑA,0337345,0,288092,0040 HIPOLITO UNANUE,Intérprete de lengua de señas peruana para EBA,6,perfil_1,105900,9540,3600
4,10,10. LIMA METROPOLITANA,4,004. USE 04 COMAS,150105,UGEL 04 COMAS,0830968,0,301625,2048 JOSE CARLOS MARIATEGUI,Intérprete de lengua de señas peruana para EBA,2,perfil_1,35300,3180,1200

In [13]:
# CAS MENSUAL
# =====================

# Generar las columnas de costos para cada mes
meses = ['enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre']

def calcular_costo_cas(row, mes):
    # Si el perfil es 'perfil_1', se usa 'rem_1', de lo contrario 'rem_2'
    if row['perfil_cod'] == 'perfil_1':
        # Accessing rem_1 and nc from outer scope
        return (remuneraciones[0]) * row['PEAS']
    else:
        # Accessing rem_2 and nc from outer scope
        return (remuneraciones[1]) * row['PEAS']

# Bucle para crear las columnas de costos para cada mes
for mes in meses:
    col_name = f'cas_{mes}'  # Nombre de la columna como 'cas_enero', 'cas_febrero', etc.
    peas_siaf[col_name] = peas_siaf.apply(calcular_costo_cas, axis=1, mes=mes)

peas_siaf['cas_enero'] = 0
peas_siaf['cas_febrero'] = 0


# ESSALUD MENSUAL
def calcular_costo_essalud(row, mes):
    # Si el perfil es 'perfil_1', se usa 'rem_1', de lo contrario 'rem_2'
    if row['perfil_cod'] == 'perfil_1':
        # Accediendo a la rem_1 y nc
        return resultados[0]*row['PEAS']
    else:
        # Accediendo a la rem_2 y nc
        return resultados[1]*row['PEAS']


# Bucle para crear las columnas de costos para cada mes
for mes in meses:
    col_name = f'essalud_{mes}'
    peas_siaf[col_name] = peas_siaf.apply(calcular_costo_essalud, axis=1, mes=mes)

peas_siaf['essalud_enero'] = 0
peas_siaf['essalud_febrero'] = 0


# AGUINALDO MENSUAL
def calcular_costo_aguinaldo(row, mes):
    # Si el perfil es 'perfil_1', se usa 'rem_1', de lo contrario 'rem_2'
    if row['perfil_cod'] == 'perfil_1':
        # Accediendo a la rem_1 y nc
        return agui_1*row['PEAS']
    else:
        # Accediendo a la rem_2 y nc
        return agui_2*row['PEAS']

# Bucle para crear las columnas de costos para cada mes
for mes in meses:
    col_name = f'aguinaldo_{mes}'
    peas_siaf[col_name] = peas_siaf.apply(calcular_costo_aguinaldo, axis=1, mes=mes)

peas_siaf['aguinaldo_enero'] = 0
peas_siaf['aguinaldo_febrero'] = 0
peas_siaf['aguinaldo_marzo'] = 0
peas_siaf['aguinaldo_abril'] = 0
peas_siaf['aguinaldo_mayo'] = 0
peas_siaf['aguinaldo_junio'] = 0
peas_siaf['aguinaldo_agosto'] = 0
peas_siaf['aguinaldo_septiembre'] = 0
peas_siaf['aguinaldo_octubre'] = 0
peas_siaf['aguinaldo_noviembre'] = 0



cas = ['cas_anual','cas_enero','cas_febrero','cas_marzo','cas_abril','cas_mayo','cas_junio',
       'cas_julio','cas_agosto','cas_septiembre','cas_octubre','cas_noviembre','cas_diciembre']

essalud = ['essalud_anual','essalud_enero','essalud_febrero','essalud_marzo','essalud_abril','essalud_mayo','essalud_junio',
           'essalud_julio','essalud_agosto','essalud_septiembre','essalud_octubre','essalud_noviembre','essalud_diciembre']

aguinaldo = ['aguinaldo_anual','aguinaldo_enero','aguinaldo_febrero','aguinaldo_marzo','aguinaldo_abril','aguinaldo_mayo','aguinaldo_junio',
           'aguinaldo_julio','aguinaldo_agosto','aguinaldo_septiembre','aguinaldo_octubre','aguinaldo_noviembre','aguinaldo_diciembre']

var = ['PLIEGO','NOM_PLIEGO','EJECUTORA','NOM_UE','CODOOII','UGEL','COD_MOD','ANEXO','CODLOCAL','CEN_EDU','Perfil', 'PEAS','perfil_cod']


peas_siaf_long = pd.melt(peas_siaf, id_vars=var, value_vars=cas+essalud+aguinaldo, var_name='detalle', value_name='costo')


peas_siaf_long['enero'] = 0
peas_siaf_long['febrero'] = 0
peas_siaf_long['marzo'] = 0
peas_siaf_long['abril'] = 0
peas_siaf_long['mayo'] = 0
peas_siaf_long['junio'] = 0
peas_siaf_long['julio'] = 0
peas_siaf_long['agosto'] = 0
peas_siaf_long['septiembre'] = 0
peas_siaf_long['octubre'] = 0
peas_siaf_long['noviembre'] = 0
peas_siaf_long['diciembre'] = 0
peas_siaf_long['costo_anual'] = 0

peas_siaf_long['enero'] = np.where(peas_siaf_long['detalle'].str.contains('enero'), peas_siaf_long['costo'], peas_siaf_long['enero'])
peas_siaf_long['febrero'] = np.where(peas_siaf_long['detalle'].str.contains('febrero'), peas_siaf_long['costo'], peas_siaf_long['febrero'])
peas_siaf_long['marzo'] = np.where(peas_siaf_long['detalle'].str.contains('marzo'), peas_siaf_long['costo'], peas_siaf_long['marzo'])
peas_siaf_long['abril'] = np.where(peas_siaf_long['detalle'].str.contains('abril'), peas_siaf_long['costo'], peas_siaf_long['abril'])
peas_siaf_long['mayo'] = np.where(peas_siaf_long['detalle'].str.contains('mayo'), peas_siaf_long['costo'], peas_siaf_long['mayo'])
peas_siaf_long['junio'] = np.where(peas_siaf_long['detalle'].str.contains('junio'), peas_siaf_long['costo'], peas_siaf_long['junio'])
peas_siaf_long['julio'] = np.where(peas_siaf_long['detalle'].str.contains('julio'), peas_siaf_long['costo'], peas_siaf_long['julio'])
peas_siaf_long['agosto'] = np.where(peas_siaf_long['detalle'].str.contains('agosto'), peas_siaf_long['costo'], peas_siaf_long['agosto'])
peas_siaf_long['septiembre'] = np.where(peas_siaf_long['detalle'].str.contains('septiembre'), peas_siaf_long['costo'], peas_siaf_long['septiembre'])
peas_siaf_long['octubre'] = np.where(peas_siaf_long['detalle'].str.contains('octubre'), peas_siaf_long['costo'], peas_siaf_long['octubre'])
peas_siaf_long['noviembre'] = np.where(peas_siaf_long['detalle'].str.contains('noviembre'), peas_siaf_long['costo'], peas_siaf_long['noviembre'])
peas_siaf_long['diciembre'] = np.where(peas_siaf_long['detalle'].str.contains('diciembre'), peas_siaf_long['costo'], peas_siaf_long['diciembre'])

peas_siaf_long['costo_anual'] = np.where(peas_siaf_long['detalle'].str.contains('anual'), peas_siaf_long['costo'], peas_siaf_long['costo_anual'])


peas_siaf_long['correlativo'] = '1.1.13.1.2. CONTRATO ADMINISTRATIVO DE SERVICIOS - TRANSITORIO'
peas_siaf_long['correlativo'] = np.where(peas_siaf_long['detalle'].str.contains('essalud'), '1.3.1.1.15. CONTRIBUCIONES A ESSALUD DE CONTRATO ADMINISTRATIVO DE SERVICIOS', peas_siaf_long['correlativo'])
peas_siaf_long['correlativo'] = np.where(peas_siaf_long['detalle'].str.contains('aguinaldo'), '1.1.9.1.4. AGUINALDOS DE CONTRATO ADMINISTRATIVO DE SERVICIOS', peas_siaf_long['correlativo'])


# realizamos un groupby

# Seleccionar las columnas clave para agrupar
group_columns = ['PLIEGO', 'NOM_PLIEGO', 'EJECUTORA', 'NOM_UE', 'CODOOII', 'UGEL','correlativo']

# Columnas numéricas para las cuales se calcularán las sumas
sum_columns = ['enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio',
               'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre','costo_anual']

# Realizamos el groupby y suma de los valores
siaf = peas_siaf_long.groupby(group_columns)[sum_columns].sum().reset_index()


# agregamos la EFP
siaf['COD_PPR'] = '9002'
siaf['programa_presupuestal'] = '9002. ASIGNACIONES PRESUPUESTARIAS QUE NO RESULTAN EN PRODUCTOS'
siaf['COD_PRODUCTO'] = '3999999'
siaf['producto_proy'] = '3999999. SIN PRODUCTO'
siaf['COD_ACTIVIDAD'] = '5001924'
siaf['actividad_obra'] = '5001924. DESARROLLO DE LA EDUCACION BASICA ALTERNATIVA'
siaf['COD_FUNCION'] = '22'
siaf['funcion'] = '22. EDUCACION'
siaf['COD_DIV_FUNC'] = '47'
siaf['division_funcional'] = '047. EDUCACION BASICA'
siaf['COD_GRUPO_FUNC'] = '106'
siaf['grupo_funcional'] = '0106. EDUCACION BASICA ALTERNATIVA'


# importamos la base de genericas
generica = pd.read_excel('D:/2025/IAP/Interpretes DEBA/input/base_generica.xlsx', sheet_name='Genericas')

siaf_2 = pd.merge(siaf, generica, on = 'correlativo', how='left')

siaf_2['intervencion'] = 'Intérpretes de señas DEBA'
siaf_2['COD_INTERVENCION'] = '024'
siaf_2['COD_FTE'] = '1'
siaf_2['componente'] = 'CONTRATACION DE PERSONAL CAS'


# empleamos regex para crear los códigos de los correlativos
import re

def extract_codes(corr):
  """Extracts codes from a string using regex.

  Args:
    corr: The input string containing the code.

  Returns:
    A dictionary containing the extracted codes.
  """
  codes = {}
  match = re.match(r"([0-9]*)\.([0-9]*)\.([0-9]*)\.([0-9]*)\.([0-9]*)", corr)
  if match:
    codes['cod_gen'] = match.group(1)
    codes['cod_subgg'] = match.group(2)
    codes['cod_subgg2'] = match.group(3)
    codes['cod_espec'] = match.group(4)
    codes['cod_espec2'] = match.group(5)
  return codes


siaf_2['cod_gen'] = siaf_2['corr'].apply(extract_codes).apply(lambda x: x['cod_gen'])
siaf_2['cod_subgg'] = siaf_2['corr'].apply(extract_codes).apply(lambda x: x['cod_subgg'])
siaf_2['cod_subgg2'] = siaf_2['corr'].apply(extract_codes).apply(lambda x: x['cod_subgg2'])
siaf_2['cod_espec'] = siaf_2['corr'].apply(extract_codes).apply(lambda x: x['cod_espec'])
siaf_2['cod_espec2'] = siaf_2['corr'].apply(extract_codes).apply(lambda x: x['cod_espec2'])


# Definir el orden de las columnas
column_order_siaf = ['PLIEGO','NOM_PLIEGO','EJECUTORA','NOM_UE','CODOOII','UGEL',
                     'COD_PPR','programa_presupuestal','COD_PRODUCTO','producto_proy','COD_ACTIVIDAD','actividad_obra',
                     'COD_FUNCION','funcion','COD_DIV_FUNC','division_funcional','COD_GRUPO_FUNC','grupo_funcional',
                     'cod_gen','generica','cod_subgg','subgenerica','cod_subgg2','subgenerica_det','cod_espec','especifica','cod_espec2','especifica_det',
                     'componente','corr','correlativo',
                     'enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre','costo_anual',
                     'COD_FTE','intervencion','COD_INTERVENCION']

# Reordenar las columnas del DataFrame
siaf_2 = siaf_2[column_order_siaf]


# renombrar campos
column_renames = ['COD_PLIEGO','nom_pliego','COD_UE','nom_ue','cod_ugel','ugel',
                  'COD_PPR','programa_presupuestal','COD_PROD','producto_proy','COD_ACT','actividad_obra',
                  'COD_FUN','funcion','COD_DIV_FUN','division_funcional','COD_GRUPFUN','grupo_funcional',
                  'COD_GEN','generica','COD_SUBG','subgenerica','COD_SUBGT','subgenerica_det','COD_ESP','especifica','COD_ESPT','especifica_det',
                  'componente','corr','correlativo',
                  'enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre','costo_anual',
                  'COD_FTE','intervencion','COD_INTERVENCION']

siaf_2 = siaf_2.rename(columns=dict(zip(siaf_2.columns, column_renames)))


# exportar el resultado a nivel de Ugel (Formato Minedu)
siaf_2.to_excel('D:/2025/IAP/Interpretes DEBA/output/MEF/DEBA_2025_siaf_Minedu.xlsx', index=False)
siaf_2.to_stata('D:/2025/IAP/Interpretes DEBA/output/MEF/DEBA_2025_siaf_Minedu.dta', write_index=False)